### ISSUE TITLE
Error when uploading files

### ISSUE THREAD

**Issue by kommersz** [cloudfoundry-incubator/multiapps-cli-plugin#97] opened 2020-01-25 13:28 UTC
### Description
When trying to run cf deploy on an mtar file 248 MB in size, the upload fails somewhere halfway with the following error:

> Uploading 1 files...

_\<mtar file here\>_

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a1a92]
>goroutine 164 [running]:
io.copyBuffer(0x0, 0x0, 0xa9faa0, 0xc0002ea330, 0xc000668000, 0x8000, 0x8000, 0xa9edc0, 0xc0000ac0a0, 0x0)
        /usr/local/go/src/io/io.go:404 +0x1d2
io.Copy(...)
        /usr/local/go/src/io/io.go:364
github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/go-openapi/runtime/client.(*request).BuildHTTP.func1(0xc0002ae660, 0xc000716140, 0xc00013caf0)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/go-openapi/runtime/client/request.go:140 +0x392
created by github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/go-openapi/runtime/client.(*request).BuildHTTP
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/go-openapi/runtime/client/request.go:113 +0x590

### Your environment
*	MultiApps CF CLI Plugin version - 2.2.1 - the most recent, as of now
*	which CF vendor is used - SAP Cloud Platform

**Comment by ddonchev** [comment] 2020-01-26 09:02
Hi @kommersz, & thank you for reporting this!

I've not yet retested manually, but an integration test doing a 4GB MTArs deployment from an ubuntu linux container is green. 

This may be an issue relevant to the concrete os specific binary of the plugin. What is the environment you're testing in? 

Additionally, when the object store persistence was first enabled for Azure landscapes, a misconfiguration of the native service had resulted in a similar issue - no chunks larger than ~250M could be persisted. This should have been resolved since a week or so.

**Comment by ddonchev** [comment] 2020-04-18 19:25
Assuming the issue is resolved, I'm closing it.
Please feel free to reopen.

**Closed by ddonchev** 2020-04-18 19:25 UTC
